# Generated by Django 2.0.3 on 2018-07-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='test_teacher',
        ),
    ]
