# Generated by Django 2.0.3 on 2018-07-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0002_auto_20180726_2108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='linux_teacher',
        ),
    ]
